spring.application.name=finkiopendesk

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=${SENDGRID_SMTP_API_KEY}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=100000
spring.mail.properties.mail.smtp.timeout=100000
spring.mail.properties.mail.smtp.writetimeout=100000

jwt.activation.secret=${JWT_ACTIVATION_SECRET}
jwt.login.secret=${JWT_LOGIN_SECRET}

spring.config.import=optional:file:./.env
server.port=${PORT:8080}