INSERT INTO profession (name, alternative_name, description) VALUES
    ('Software Engineer', NULL, 'Designs, develops, tests, and maintains software systems across platforms and technologies, ensuring quality, scalability, and performance.'),
    ('Full-Stack Developer', NULL, 'Builds both front-end and back-end components of web applications, handling databases, servers, and user interfaces.'),
    ('Frontend Developer', NULL, 'Specializes in creating user-facing components, designing responsive interfaces and seamless interactions for web applications.'),
    ('Backend Developer', NULL, 'Develops server-side logic, APIs, and database management, ensuring data security and application scalability.'),
    ('Web Developer', NULL, 'Creates and maintains websites and web applications, focusing on usability, performance, and accessibility.'),
    ('Mobile App Developer', NULL, 'Designs and develops mobile applications for iOS and Android platforms, optimizing performance and user experience.'),
    ('Game Developer', NULL, 'Builds video games, including gameplay mechanics, graphics, AI, and performance optimization across platforms.'),
    ('Embedded Systems Developer', NULL, 'Designs software for embedded systems in devices, integrating hardware and software for optimal functionality.'),
    ('API Developer', NULL, 'Creates and maintains application programming interfaces, enabling software components to communicate effectively.'),
    ('Data Analyst', NULL, 'Analyzes and interprets data to provide actionable insights, reports, and visualizations for decision-making.'),
    ('Data Scientist', NULL, 'Uses statistical analysis, machine learning, and data modeling to solve complex problems and extract insights.'),
    ('Data Engineer', NULL, 'Builds and maintains data pipelines, databases, and architecture for efficient data processing and analysis.'),
    ('AI Engineer', NULL, 'Designs and implements artificial intelligence models, including machine learning and neural network solutions.'),
    ('Machine Learning Engineer', 'AI Engineer', 'Develops, trains, and deploys machine learning models, optimizing algorithms for predictive analytics and AI applications.'),
    ('NLP Engineer', 'AI Engineer', 'Creates natural language processing models for text analysis, chatbots, translation, and speech recognition.'),
    ('Computer Vision Engineer', 'AI Engineer', 'Develops computer vision applications for image and video analysis, object recognition, and visual AI systems.'),
    ('Business Intelligence Analyst', NULL, 'Analyzes business data, creates dashboards, and supports strategic decision-making with actionable insights.'),
    ('DevOps Engineer', NULL, 'Integrates development and operations, automating workflows, deployment, and continuous integration processes.'),
    ('Cloud Engineer', NULL, 'Designs, implements, and manages cloud infrastructure, ensuring scalability, security, and performance.'),
    ('Infrastructure Engineer', NULL, 'Builds and maintains IT infrastructure, including servers, networks, and system resources.'),
    ('System Administrator', 'Network Administrator', 'Manages and maintains IT systems and networks, ensuring availability, security, and performance.'),
    ('Cybersecurity Engineer', NULL, 'Protects systems and data from cyber threats by implementing security protocols and monitoring networks.'),
    ('SOC Analyst', 'Security Analyst', 'Monitors security operations, analyzes threats, and responds to incidents to safeguard organizational assets.'),
    ('Ethical Hacker', 'Penetration Tester', 'Tests and evaluates system security by identifying vulnerabilities and recommending improvements.'),
    ('Digital Forensics Analyst', NULL, 'Investigates cyber incidents, recovering and analyzing digital evidence for legal and security purposes.'),
    ('Database Administrator', 'Database Engineer', 'Manages databases, ensuring data integrity, security, and optimal performance for applications.'),
    ('ERP Technical Specialist', 'CRM Technical Specialist', 'Customizes, implements, and supports enterprise and customer management software solutions.'),
    ('UI/UX Designer', NULL, 'Designs user interfaces and experiences for software, focusing on usability, accessibility, and aesthetics.'),
    ('Product Designer', 'UX Researcher', 'Creates product designs and user research to optimize user satisfaction and functionality.'),
    ('Accessibility Specialist', NULL, 'Ensures software and digital products are accessible to people with disabilities, following best practices.'),
    ('QA Engineer', 'Software Tester', 'Tests software functionality, identifies bugs, and ensures quality standards are met.'),
    ('Test Automation Engineer', NULL, 'Develops automated tests to verify software quality, performance, and reliability efficiently.'),
    ('Performance Tester', NULL, 'Evaluates system performance under various conditions, identifying bottlenecks and optimization opportunities.'),
    ('Blockchain Developer', 'Web3 Developer', 'Builds decentralized applications, smart contracts, and blockchain solutions for secure digital transactions.'),
    ('AR/VR Developer', 'Augmented/Virtual Reality Developer', 'Designs and develops AR/VR applications, integrating immersive technologies and interactive experiences.'),
    ('IoT Engineer', NULL, 'Creates solutions for connected devices, integrating sensors, networks, and software systems.'),
    ('Robotics Engineer', NULL, 'Designs and develops robots and automated systems for industrial, commercial, or research purposes.'),
    ('Quantum Computing Engineer', 'HPC Engineer', 'Develops algorithms and software for quantum computing and high-performance computing systems.'),
    ('Bioinformatics Engineer', NULL, 'Combines biology, computer science, and data analysis to process and interpret biological data.'),
    ('IT Support Specialist', 'Help Desk Technician', 'Provides technical assistance to users, resolving hardware, software, and network issues.'),
    ('Technical Support Engineer', NULL, 'Supports users and customers by troubleshooting technical problems and implementing solutions.'),
    ('Solutions Architect', NULL, 'Designs software and system architectures to meet business and technical requirements.'),
    ('Technical Writer', NULL, 'Creates clear documentation, manuals, and guides for software, systems, and technical processes.');


INSERT INTO subject (name, description) VALUES
    ('Дизајн на Интеракција Човек-Компјутер', 'ДНИЧК'),
    ('Објектно-ориентирано Програмирање', 'ООП'),
    ('Бизнис Статистика', 'БС'),
    ('Основи на Веб Дизајн', 'ОнВД'),
    ('Компјутерски Мрежи и Безбедност', 'КМиБ'),
    ('Претприемништво', 'Претприемништво'),
    ('Управување со ИКТ Проекти', 'УИКТП'),
    ('Менаџмент Информациски Системи', 'МеИС'),
    ('Тестирање на Софтвер', 'ТнС'),
    ('Напреден Веб Дизајн', 'Запознавање со напредните технологии во областа на веб дизајнот и развојот на модерни динамички веб апликации.'),
    ('Компјутерска Анимација', 'Покривање на теориските основи и концепти на 2D и 3D компјутерска графика.'),
    ('Компјутерска Графика', 'Создавање, моделирање, текстурирање и анимација на дигитални сцени.'),
    ('Електронска и Мобилна Трговија', 'ЕМТ'),
    ('Структурно Програмирање', 'СП'),
    ('Бизнис и Менаџмент', 'БиМ'),
    ('Вовед во Компјутерските Науки', 'ВвКН'),
    ('Дискретна Математика', 'ДМ'),
    ('Архитектура и Организација на Компјутери', 'АОК'),
    ('ИТ Системи за учење', 'ИТСУ'),
    ('Калкулус', 'Калк'),
    ('Калкулус 2', 'Калк2'),
    ('Компјутерски Компоненти', 'КК'),
    ('Дигитизација', 'Дигит'),
    ('Визуелизација', 'Визуелизација'),
    ('Компјутерска Етика', 'КЕ'),
    ('Мултимедиски Мрежи', 'ММ'),
    ('Вградливи Микропроцесорски Системи', 'ВМС'),
    ('Виртуелизација', 'Виртуелизација'),
    ('Софтверски Квалитет и Тестирање', 'СКиТ'),
    ('Анализа и Дизајн на Информациски Системи', 'АиДнИС'),
    ('Вовед во Паметни Градови', 'ВвПГ'),
    ('Вовед во Препознавање на Облици', 'ВвПО'),
    ('Дигитална Постпродукција', 'ДП'),
    ('Имплементација на Системи со Слободен и Отворен Код', 'ИнССиОК'),
    ('Иновации во ИКТ', 'ИвИКТ'),
    ('Интернет на Нештата', 'ИнН'),
    ('Методологија на истражувањето во ИКТ', 'МнИвИКТ'),
    ('Мобилни Информациски Системи', 'МобИС'),
    ('Мобилни Платформи и Програмирање', 'МПиП'),
    ('Напредна Интеракција Човек-Компјутер', 'НИЧК'),
    ('Пресметување во Облак', 'ПвО'),
    ('Програмирање на Видео Игри', 'ПнВИ'),
    ('Програмски Парадигми', 'ПП'),
    ('Системи за Поддршка при Одлучувањето', 'СзПпО'),
    ('Софтвер за Вградливи Системи', 'СзВС'),
    ('Софтверски Дефинирани Мрежи', 'СДМ'),
    ('Социјални Мрежи и Медиуми', 'СМиМ'),
    ('Креативни Вештини за Решавање Проблеми', 'КВР'),
    ('Објектно-Ориентирана Анализа и Дизајн', 'ООАиД'),
    ('Алгоритми и Податочни Структури', 'АиПС'),
    ('Економија за ИКТ Инженери', 'ЕИКТИ'),
    ('Интернет Програмирање на Клиентска Страна', 'ИПнКС'),
    ('Напредно Програмирање', 'НП'),
    ('Управување со Техничката Поддршка', 'УТП'),
    ('Шаблони за Дизајн на Кориснички Интерфејси', 'ШДнКИ'),
    ('Оперативни Системи', 'ОС'),
    ('Софтверско Инженерство', 'СИ'),
    ('Анализа на Софтверските Барања', 'АнСБ'),
    ('Безжични и Мобилни Системи', 'БиМС'),
    ('Вештачка Интелигенција', 'ВИ'),
    ('Визуелно Програмирање', 'ВизП'),
    ('Вовед во Екоинформатиката', 'ВВЕ'),
    ('Вовед во Случајни Процеси', 'ВвСП'),
    ('Дизајн на Алгоритми', 'ДнА'),
    ('Е-Влада', 'Е-влада'),
    ('Електрични Кола', 'ЕК'),
    ('Интернет Технологии', 'ИТ'),
    ('Концепти на Информатичко Општество', 'КнИО'),
    ('Медиуми и Комуникации', 'МиК'),
    ('Бази на Податоци', 'БнП'),
    ('Веб Програмирање', 'ВП'),
    ('Вовед во Науката за Податоци', 'ВвНП'),
    ('Администрација на Системи', 'АнС'),
    ('Дизајн и Архитектура на Софтвер', 'ДиАнС'),
    ('Информациска Безбедност', 'ИБ'),
    ('Компјутерски Звук, Говор и Музика', 'КЗГиМ'),
    ('Линеарна Алгебра и Примени', 'ЛАиП'),
    ('Основи на Роботиката', 'ОнР'),
    ('Агентно-Базирани Системи', 'АБС'),
    ('Безжични Мултимедиски Системи', 'БМС'),
    ('Вовед во Мрежна Наука', 'ВвМН'),
    ('Географски Информациски Системи', 'ГИС'),
    ('Континуирана Интеграција и Испорака', 'КИИИ'),
    ('Машинско Учење', 'МУ'),
    ('Мултимедиски Системи', 'МС'),
    ('Податочно Рударство', 'ПР'),
    ('Сервисно Ориентирани Архитектури', 'СОА'),
    ('Софтверски Дефинирана Безбедност', 'СДБ'),
    ('Автономна Роботика', 'АР'),
    ('Администрација на Бази на Податоци', 'АнБнП'),
    ('Веб Базирани Системи', 'ВБС'),
    ('Вовед во Биоинформатиката', 'ВвБ'),
    ('Машинска Визија', 'МВ');
